### PR TITLE
🌱 update to cso v0.1.0-alpha.5

### PR DESCRIPTION
**Pull request by kranurag7**
this commit udpates to the new release of CSO.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by kranurag7 — COMMENTED** [review]
README compatibility docs are not updated via this PR because I've not tested it.

**Review by michal-gubricky — APPROVED** [review]
LGTM. I also tested it with the tilt(`local_mode=False`) and all seems to be working fine.

**Review by chess-knight — COMMENTED** [review]
Can you add this version also to the compatibility matrix(README)?

**Review by chess-knight — APPROVED** [review]

**Review by matofeder — APPROVED** [review]
lgmt

**Pull request merged**
